name: accessory_app
description: "Accessory App"
publish_to: "none"

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  # 필요 시 확장:
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.0
  cloud_functions: ^5.1.3
  image_picker: ^1.1.2
  flutter_image_compress: ^2.3.0
  async: ^2.11.0   # (Pool 사용: 동시 업로드 개수 제한)
  pool: ^1.5.1
  scrollable_positioned_list: ^0.3.8
  shared_preferences: ^2.3.1
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.13.1
  firebase_messaging: ^15.0.4
  flutter_local_notifications: ^17.2.4
  file_picker: ^8.0.5
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon1.png"        # 정사각형 1024x1024 권장
  remove_alpha_ios: true
  android_13:
    image: "assets/icon/app_icon_monochrome.png"  # 432x432 권장(투명 단색)
