name: accessory_app
description: "Accessory App"
publish_to: "none"

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  # 필요 시 확장:
  image_picker: ^1.1.2
  http: ^1.2.2
  image: ^4.1.0
  video_player: ^2.9.1
  flutter_image_compress: ^2.3.0
  video_compress: ^3.1.3
  async: ^2.11.0   # (Pool 사용: 동시 업로드 개수 제한)
  pool: ^1.5.1
  scrollable_positioned_list: ^0.3.8
  shared_preferences: ^2.3.1
  file_picker: ^8.0.5
  url_launcher: ^6.3.0
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  firebase_storage: ^13.0.4
  cloud_functions: ^6.0.4
  flutter_launcher_icons: ^0.13.1
  cached_network_image: ^3.3.1
  visibility_detector: ^0.4.0+2
  flutter_staggered_grid_view: ^0.7.0

  firebase_messaging: ^16.0.4
  flutter_local_notifications: ^19.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/appbar/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon1.png"        # 정사각형 1024x1024 권장
  remove_alpha_ios: true
  android_13:
    image: "assets/icon/app_icon_monochrome.png"  # 432x432 권장(투명 단색)
